### ISSUE TITLE
Suggestion: Remove second alias (unneeded?)

### ISSUE THREAD

**Issue by webbertakken** [Tanimodori/viteburner-template#2]
I'm not sure why the second alias (` "/src/*": ["./src/*"],`) is needed. If it's not strictly necessary shall we just remove it?

https://github.com/Tanimodori/viteburner-template/blob/e1968b7d5e08bf20f1e5615c9cdd229cb0fd5d78/tsconfig.json#L18

**Comment by Tanimodori** [comment]
Technically it is not necessary. Surely the project will work without it.

But an alias is just for convenience. The idea behind whole `vite` ecosystem is **convenience** with features like zero-config and easy migrations. This project aims at those who use [the official template](https://github.com/bitburner-official/typescript-template) and others, where the import is like `import foo from 'src/foo'` with no leading slash before `src` (That's the only way that both `tsc` and `bitburner` are happy without using `acron` for rewriting import strings). I hope that less effort is done when people migrate from other templates. So I provided this alias so few code base changes would be made.

Initially I wanted to use the same `src/*` but met with some technical problems with `vite` (Sorry I don't remember the details clearly as I didn't document that). So I finally used `/src/*`. There are some people claim that `@/*` or `/@/*` is ugly so `/src/*` may be the one they finally go for.
